name: flutter_ecommerce
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: 6.0.0
  gap: ^3.0.1
  go_router: ^13.2.0
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.4
  dartz: ^0.10.1
  dio: ^5.8.0+1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.9.0
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.3
  circle_nav_bar: ^2.2.0
  image_picker: ^1.0.8
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.6
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
